import BaseElement from './BaseElement/BaseElement';
import Label from './subviews/Label/Label';
import { PanelOptions } from './subviews/Panel/Panel';
import { IEventListener, PossibleEvents } from '../EventManager/EventManager';
declare type ViewOptions = {
    minMaxLabels: boolean;
    valueLabels: boolean;
    vertical: boolean;
    range: boolean;
    scale: boolean;
    scaleIntervals: number;
    panel: boolean;
};
declare class View extends BaseElement<'div'> {
    static defaults: Readonly<ViewOptions>;
    private eventManager;
    private slider;
    private track;
    private range;
    private input;
    private thumbLeft;
    private thumbRight?;
    private scale?;
    private scaleIntervals;
    private minLabel?;
    private maxLabel?;
    private valueLabelLeft?;
    private valueLabelRight?;
    private valueLabelCommon?;
    private vertical?;
    private labelsContainer?;
    private panel?;
    constructor(component: HTMLDivElement, options?: Partial<ViewOptions>);
    static validate(options: ViewOptions): ViewOptions;
    subscribe(listener: IEventListener): void;
    inform<E extends keyof PossibleEvents>(eventType: E, data: PossibleEvents[E]): void;
    setMinValue(min: number): void;
    setMaxValue(max: number): void;
    setLeftValue(value: number, percent: number): void;
    setRightValue(value: number, percent: number): void;
    updateInput(value1: number, value2?: number | null): void;
    handleLeftInput(x: number, y: number): void;
    handleRightInput(x: number, y: number): void;
    addScale(min: number, max: number): void;
    removeScale(): void;
    getScaleIntervals(): number;
    handleScaleOrTrackClick(x: number, y: number): void;
    fixLabelsContainerWidthForVertical(): void;
    fixLabelsContainerHeightForHorizontal(): void;
    setPanelValues(options: PanelOptions): void;
    updatePanelFrom(value: number): void;
    updatePanelTo(value: number | ''): void;
    updatePanelScaleIntervals(value: number | ''): void;
    updatePanelStep(value: number): void;
    updatePanelMin(value: number): void;
    updatePanelMax(value: number): void;
    setLeftFromOutside(value: number): void;
    setRightFromOutside(value: number): void;
    setMinFromOutside(value: number): void;
    setMaxFromOutside(value: number): void;
    setStepFromOutside(value: number): void;
    toggleOrientation(): void;
    toggleRange(): void;
    toggleScale(): void;
    setScaleIntervals(value: number): void;
    toggleValueLabels(): void;
    toggleMinMaxLabels(): void;
    hasLabels(): boolean;
    hasScale(): boolean;
    hasMinMaxLabels(): boolean;
    hasValueLabels(): boolean;
    hasPanel(): boolean;
    isRange(): boolean;
    isVertical(): boolean;
    getTrackLength(): number;
    getOptions(): ViewOptions;
    private render;
    private destroy;
    mergeLabels(): void;
    splitLabels(): void;
    hideMinLabel(): void;
    showMinLabel(): void;
    hideMaxLabel(): void;
    showMaxLabel(): void;
    getDistanceBetweenTwoLabels(label1: Label, label2: Label): number;
    getDistanceBetweenValueLabels(): number | undefined;
    getDistanceBetweenLeftValueLabelAndMinLabel(): number | undefined;
    getDistanceBetweenLeftValueLabelAndMaxLabel(): number | undefined;
    getDistanceBetweenRightValueLabelAndMaxLabel(): number | undefined;
    private whichThumbIsNearer;
    private addSmoothTransition;
    private removeSmoothTransition;
    private collectLabels;
}
export default View;
//# sourceMappingURL=View.d.ts.map