declare type PanelOptions = {
    min: number;
    max: number;
    step: number;
    from: number;
    to: number | null;
    vertical: boolean;
    range: boolean;
    scale: boolean;
    scaleIntervals: number | null;
    valueLabels: boolean;
    minMaxLabels: boolean;
};
declare class Panel {
    view: any;
    component: HTMLElement;
    min: HTMLElement;
    max: HTMLElement;
    step: HTMLElement;
    from: HTMLElement;
    to: HTMLElement;
    vertical: HTMLElement;
    range: HTMLElement;
    scale: HTMLElement;
    scaleIntervals: HTMLElement;
    valueLabels: HTMLElement;
    minMaxLabels: HTMLElement;
    constructor();
    registerWith(view: any): void;
    setValues(options: PanelOptions): void;
    updateFrom(value: number): void;
    updateTo(value: number | ''): void;
    updateStep(value: number): void;
    updateScaleIntervals(value: number | ''): void;
    private render;
    private static addLabel;
    private setTypes;
    private setAttributes;
    private setCheckMarks;
    private static calcStepMin;
    private updateAttributesAfterFromChange;
    private updateAttributesAfterToChange;
    private updateAttributesAfterStepChange;
    private updateAttributesAfterMinChange;
    private updateAttributesAfterMaxChange;
    private handleMinChange;
    private handleMaxChange;
    private handleStepChange;
    private handleFromChange;
    private handleToChange;
    private handleVerticalChange;
    private handleRangeChange;
    private handleScaleChange;
    private handleScaleIntervalsChange;
    private handleValueLabelsChange;
    private handleMinMaxLabelsChange;
    private static toggleCheckbox;
    private attachEventHandlers;
}
export { PanelOptions, Panel };
//# sourceMappingURL=Panel.d.ts.map